vich_uploader:
    db_driver: orm

    mappings:
       recipe_image:
           uri_prefix: '%app.path.recipe_image%'
           upload_destination: '%kernel.project_dir%/public/images/recipes'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
